#!/bin/bash
DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd) # http://stackoverflow.com/a/246128/309308
if [[ "$1" =~ .*/rebase-merge/git-rebase-todo$ ]]; then
	/usr/bin/env python2 $DIR/gir.py "$1"
elif [ ! -z "$EDITOR" ]; then
	$EDITOR "$1"
else
	echo "No \$EDITOR set"
	exit 1
fi
